const app=document.querySelector('#app'), prog=document.querySelector('#progress'), creditEl=document.querySelector('#credits');
let credits=0; const awarded=new Set(); let currentClock=''; let goalsComplete=true; let goalCredit=0;
function setClock(t){currentClock=t;}
function updateCredits(){if(creditEl) creditEl.textContent=`CREDITS ${credits} / 100`;}
function award(key,n){if(!awarded.has(key)){awarded.add(key);credits=Math.min(100,credits+n);updateCredits();return `<div class=\"creditpop\">+${n} CREDITS</div>`}return '';}
function resetCredits(){credits=0;awarded.clear();updateCredits();}
const panel=html=>{app.innerHTML=`<section class="panel">${currentClock?`<div class="eyebrow globalclock">${currentClock}</div>`:''}${html}</section>`;scrollTo({top:0,behavior:'smooth'})};
const setP=(n,label='')=>prog.textContent=n?`Station ${n} / 7${label?' · '+label:''}`:'Start';
const msg=(t,g=false)=>`<div class="notice ${g?'good':'bad'}">${t}</div>`;
const meter=(n,label)=>`<div class="statusline"><b>${label}</b><span>${n} %</span></div><div class="bar"><i style="width:${n}%"></i></div>`;
const anf327=()=>`<div class="req stickyreq"><b>ANF-327 – Persönliches Überweisungslimit</b><br>0–1.000 € einschließlich: ohne zusätzliche Freigabe<br>&gt;1.000–10.000 € einschließlich: zusätzliche Freigabe erforderlich<br>&gt;10.000 €: unzulässig<br>Negative Werte: unzulässig<br>Nur ganze Eurobeträge.</div>`;
let picks=new Set();
function start(){currentClock='';resetCredits();goalsComplete=true;goalCredit=0;setP(0);panel(`<div class="eyebrow">Test-Rescue-Game</div><h1>Release 2.0</h1><h2>Release in Gefahr</h2><div class="story"><b>Montag, 08:12 Uhr.</b><br><br>In zwei Wochen soll das neue Release des Kundenportals unseres Finanzinstituts live gehen. Aber in unserem Release-Projekt haben sich einige Fehler eingeschlichen und so können wir nicht live gehen.<br><br><b>Die Aufgabe:</b> Zuerst müssen die Vorbereitungen für die Testdurchführung abgeschlossen werden. Dabei sind die aufgetretenen Probleme zu lösen und Release 2.0 wieder auf Kurs zu bringen.<br><br>Dabei können auch unvorhergesehene Dinge passieren. Dann sind passende Lösungen gefragt.<br><br><b>Bereit für die Herausforderung?</b></div><button class="primary" onclick="boot()">Release retten</button>`)}
function boot(){panel(`<div class="eyebrow">Release 2.0</div><div class="story mono">PROJEKTDATEN WERDEN GELADEN …<br><br><span class="badtext">⚠ FEHLER BEIM LADEN</span><br><br>Testplanung für Release 2.0 unvollständig.<br><br><b>Der Auftrag – Testkonzept vervollständigen</b></div><button class="primary" onclick="s1()">Testkonzept öffnen</button>`)}
function s1(){setP(1,'Woche 1 · Montag');panel(`<div class="eyebrow">Station 1 · Montag 08:12 Uhr</div><h2>Der Auftrag – Testkonzept vervollständigen</h2>${meter(43,'STAND TESTKONZEPT')}<div class="file"><b>TESTKONZEPT – RELEASE 2.0</b><br><br>Testobjekt: Kundenportal – Release 2.0 ✓<br>Testzeitraum: Vorbereitung Woche 1 · Durchführung und Abschluss Woche 2 ✓<br>Testziele: <span class="badtext">DATEN BESCHÄDIGT</span><br>Testumfang: <span class="badtext">DATEN BESCHÄDIGT</span><br>Testumgebung: <span class="badtext">DATEI GELÖSCHT</span><br>Testüberwachung und Teststeuerung: <span class="badtext">DATEN BESCHÄDIGT</span></div><button class="primary" onclick="s1goals()">Testziele prüfen</button>`)}
function s1goals(){picks.clear();let a=[
'Informationen über die Qualität von Release 2.0 gewinnen.',
'Nachweisen, dass Release 2.0 vollständig fehlerfrei ist.',
'Prüfen, ob festgelegte Anforderungen erfüllt sind.',
'Fehlerzustände und Fehlerwirkungen aufdecken.',
'Sicherstellen, dass nach Produktivsetzung niemals Fehlerwirkungen auftreten.',
'Informationen als Grundlage für Entscheidungen bereitstellen.',
'Alle gefundenen Fehlermeldungen müssen vor Testbeginn behoben sein.',
'Jeder Testfall muss von zwei Personen ausgeführt werden.',
'Die Testdurchführung darf ausschließlich positive Ergebnisse erzeugen.'
];panel(`<div class="eyebrow">Station 1 · Testziele</div><h2>Testziele vervollständigen</h2><div class="notice">Mehrere Textfragmente gehören zum Testkonzept. Alle passenden Fragmente auswählen.</div><div class="options">${a.map((x,i)=>`<button id="g${i}" onclick="togglePick('g',${i})">${String.fromCharCode(65+i)}) ${x}</button>`).join('')}</div><button onclick="checkGoals()">Fragmente übernehmen</button><div id="fb"></div>`)}
function togglePick(prefix,i){let k=prefix+i;picks.has(k)?picks.delete(k):picks.add(k);document.querySelector('#'+k).classList.toggle('selected')}
function checkGoals(){
 const right=[0,2,3,5], wrong=[1,4,6,7,8];
 const selectedRight=right.filter(i=>picks.has('g'+i)); const selectedWrong=wrong.filter(i=>picks.has('g'+i));
 if(!picks.size){document.querySelector('#fb').innerHTML=msg('Mindestens ein Fragment auswählen.');return;}
 goalCredit=selectedRight.length; goalsComplete=selectedRight.length===4 && selectedWrong.length===0;
 if(!awarded.has('goals')){awarded.add('goals');credits+=goalCredit;updateCredits();}
 const pct=goalsComplete?57:56;
 let note=selectedWrong.length?'<br><b>Hinweis:</b> Mindestens ein ausgewähltes Fragment beschreibt kein geeignetes Testziel.':'';
 document.querySelector('#fb').innerHTML=msg(`Auswahl übernommen. ${selectedRight.length} passende Testziel-Fragmente erkannt.${note}`,selectedRight.length>0)+`<div class="creditpop">+${goalCredit} CREDITS</div>`+meter(pct,'STAND TESTKONZEPT')+`<button class="primary" onclick="s1scope()">Testumfang prüfen</button>`;
}
function s1scope(){panel(`<div class="eyebrow">Station 1 · Testumfang</div><h2>Testumfang klären</h2><div class="notice bad"><b>Folgende Notiz wurde rekonstruiert. Kann diese so in das Testkonzept übernommen werden?</b><br><br>„Für Release 2.0 testen wir nur die neuen Funktionen. Bestehende Funktionen wurden schließlich bereits getestet.“</div><table><tr><th>Bereich</th><th>Änderung</th></tr><tr><td>Persönliches Überweisungslimit</td><td>NEU</td></tr><tr><td>Profilbild</td><td>NEU</td></tr><tr><td>Umsatzsuche</td><td>GEÄNDERT</td></tr><tr><td>Elektronisches Postfach</td><td>GEÄNDERT</td></tr><tr><td>Anmeldung / Kontosperre</td><td>TECHNISCH ÜBERARBEITET</td></tr><tr><td>Persönliche Daten</td><td>TECHNISCH ÜBERARBEITET</td></tr></table><button onclick="scope(false)">Notiz übernehmen</button><button onclick="scope(true)">Notiz als fehlerhaft markieren</button><div id="fb"></div>`)}
function scope(ok){document.querySelector('#fb').innerHTML=ok?msg('✓ DATEN WURDEN KORRIGIERT',true)+award('scope',4)+`<div class="req">Neue und geänderte Funktionen sowie bestehende Funktionen, die durch Änderungen betroffen sein können, müssen bei der Testplanung berücksichtigt werden.</div>${meter(71,'STAND TESTKONZEPT')}<button class="primary" onclick="s1env()">Testumgebung prüfen</button>`:msg('Die Änderungen können auch bestehende Funktionen beeinflussen.')}
function s1env(){panel(`<div class="eyebrow">Station 1 · Testumgebung</div><h2>Testumgebung festlegen</h2><div class="notice bad">Es wurde keine Datei gefunden, aber es wurden drei mögliche Alternativen entdeckt. Welche passt zu Release 2.0?</div><div class="cards selectable-cards"><button class="card choicecard" onclick="env(false)"><h4>Anwendungstestumgebung</h4>Release 2.0 bereitstellbar; häufige neue Zustände; nicht alle angebundenen Systeme release-nah.</button><button class="card choicecard" onclick="env(true)"><h4>Zentrale Testumgebung</h4>Vorgesehener Stand; benötigte Systeme/Schnittstellen; definierte Testkonten/-daten; kontrollierte Ausgangslage.</button><button class="card choicecard" onclick="env(false)"><h4>Entwicklungsumgebung</h4>Aktuelle Komponentenstände; kurzfristige Änderungen; nicht zwingend alle Komponenten gleichzeitig verfügbar.</button></div><div id="fb"></div>`)}
function env(ok){document.querySelector('#fb').innerHTML=ok?msg('✓ DATEN WURDEN KORRIGIERT',true)+award('env',4)+meter(86,'STAND TESTKONZEPT')+`<button class="primary" onclick="s1control()">Letzten Bereich prüfen</button>`:msg('Diese Umgebung erfüllt die aufgeführten Anforderungen nicht vollständig.')}
function s1control(){panel(`<div class="eyebrow">Station 1 · Testüberwachung und Teststeuerung</div><h2>Testkonzept abschließen</h2><div class="notice bad"><b>NOTIZ GEFUNDEN</b><br><br>„Der einmal erstellte Testplan darf während der beiden Wochen nicht mehr verändert werden.“</div><div class="options"><button onclick="control(false)">Notiz bestätigen</button><button onclick="control(true)">Notiz korrigieren</button></div><div id="fb"></div>`)}
function control(ok){document.querySelector('#fb').innerHTML=ok?msg('✓ DATEN WURDEN KORRIGIERT',true)+award('control',3)+`<div class="req">Testfortschritt, Testergebnisse, Fehlermeldungen und verfügbare Ressourcen werden überwacht. Bei relevanten Abweichungen werden geeignete Steuerungsmaßnahmen getroffen und die Planung bei Bedarf angepasst.</div>${meter(100,'STAND TESTKONZEPT')}<button class="primary" onclick="s1end()">Testkonzept abschließen</button>`:msg('Ein Testplan kann bei relevanten Abweichungen angepasst werden.')}
function s1end(){let pct=goalsComplete?100:99;panel(`<div class="eyebrow">Station 1 · Abschluss</div><h2>${pct===100?'TESTKONZEPT VOLLSTÄNDIG':'TESTKONZEPT FAST VOLLSTÄNDIG'}</h2>${meter(pct,'STAND TESTKONZEPT')}<div class="notice good"><b>Testziele:</b> ${goalsComplete?'wurden vollständig wiederhergestellt':'wurden teilweise wiederhergestellt'}<br><b>Testumfang:</b> wurde repariert<br><b>Testumgebung:</b> wurde wiederhergestellt<br><b>Testüberwachung und Teststeuerung:</b> wurden wiederhergestellt</div><div class="story mono">ÄNDERUNGEN WERDEN GESPEICHERT …<br>TESTKONZEPT WIRD VALIDIERT …<br><span class="goodtext">✓ ERFOLGREICH</span></div><button class="primary" onclick="s1transition()">Weiter</button>`)}
function s1transition(){panel(`<div class="eyebrow">Montag · 17:58 Uhr</div><h2>Geschafft – das Testkonzept steht!</h2><div class="story">Doch damit ist Release 2.0 noch lange nicht gerettet. Weitere Herausforderungen warten bereits.<br><br><b>Bereit, weiterzumachen?</b></div><button class="primary" onclick="s2()">Dienstag öffnen</button>`)}
function s2(){setP(2,'Woche 1 · Dienstag');panel(`<div class="eyebrow">Station 2 · Dienstag 08:47 Uhr</div><h2>Das Testprozess-Chaos</h2>${meter(18,'TESTPROZESS KLAR')}<div class="story">Das Testkonzept steht. Bevor wir in die Testanalyse einsteigen können, gibt es noch Rückfragen zum Testprozess.</div><button class="primary" onclick="s2match()">Testprozess klären</button>`)}
function s2match(){let acts=['Tests in der Zentralen Testumgebung durchführen und tatsächliche mit erwarteten Ergebnissen vergleichen.','Testziele, Testumfang und Ressourcen festlegen.','Ergebnisse zusammenfassen, offene Punkte dokumentieren und den Testabschlussbericht erstellen.','Anforderungen an das persönliche Überweisungslimit untersuchen und testbare Merkmale identifizieren.','Testdaten und Testfälle für die Durchführung vorbereiten und verfügbar machen.','Äquivalenzklassen und Grenzwerte bestimmen und daraus Testfälle ableiten.'];let opts=['','Testplanung','Testanalyse','Testentwurf','Testrealisierung','Testdurchführung','Testabschluss'];panel(`<div class="eyebrow">Testaktivitäten</div><h2>Testaktivitäten zuordnen</h2>${acts.map((a,i)=>`<div class="req"><b>${'ABCDEF'[i]}</b> ${a}<br><select id="m${i}">${opts.map(o=>`<option>${o||'– Aktivität wählen –'}</option>`).join('')}</select></div>`).join('')}<button onclick="checkMatch()">Zuordnung prüfen</button><div id="fb"></div>`)}
function checkMatch(){let exp=['Testdurchführung','Testplanung','Testabschluss','Testanalyse','Testrealisierung','Testentwurf'];let ok=exp.every((x,i)=>document.querySelector('#m'+i).value===x);document.querySelector('#fb').innerHTML=ok?msg('Aktivitäten wurden korrekt zugeordnet',true)+award('s2match',6)+meter(52,'TESTPROZESS KLAR')+`<button class="primary" onclick="s2missing()">Fehlende Aktivität suchen</button>`:msg('Mindestens eine Tätigkeit passt nicht zur gewählten Testaktivität.')}
function s2missing(){panel(`<div class="eyebrow">Testaktivitäten</div><h2>Was fehlt im Testprozess?</h2><div class="processflow"><div>Testplanung</div><span>→</span><div>Testanalyse</div><span>→</span><div>Testentwurf</div><span>→</span><div>Testrealisierung</div><span>→</span><div>Testdurchführung</div><span>→</span><div>Testabschluss</div></div><p>Eine zentrale Aktivität fehlt. Begriff eingeben:</p><input id="missingInput" class="textinput" placeholder="Fehlende Aktivität …" autocomplete="off"><button onclick="checkMissingText()">Eingabe prüfen</button><div id="fb"></div>`)}
function checkMissingText(){let v=(document.querySelector('#missingInput').value||'').toLowerCase().replace(/[-–—]/g,' ').replace(/\s+/g,' ').trim();let ok=v.includes('testüberwachung')&&v.includes('teststeuerung');document.querySelector('#fb').innerHTML=ok?msg('Testüberwachung und Teststeuerung begleiten die Testaktivitäten.',true)+award('s2missing',4)+meter(81,'TESTPROZESS KLAR')+`<div class="processwrap"><div class="processbar">TESTÜBERWACHUNG UND TESTSTEUERUNG · BEGLEITEND</div><div class="processflow small"><div>Planung</div><span>→</span><div>Analyse</div><span>→</span><div>Entwurf</div><span>→</span><div>Realisierung</div><span>→</span><div>Durchführung</div><span>→</span><div>Abschluss</div></div></div><button class="primary" onclick="s2end()">Testprozess abschließen</button>`:msg('Der Begriff passt noch nicht. Gesucht ist die Aktivität, die den Testfortschritt und Abweichungen begleitend betrachtet.')}
function s2end(){panel(`<div class="eyebrow">Station 2 · Abschluss</div><h2>Fragen zum Testprozess geklärt</h2>${meter(100,'TESTPROZESS KLAR')}<div class="notice good">✓ Testplanung<br>✓ Testanalyse<br>✓ Testentwurf<br>✓ Testrealisierung<br>✓ Testdurchführung<br>✓ Testabschluss<br>✓ Testüberwachung und Teststeuerung begleitend</div><button class="primary" onclick="s2transition()">Weiter</button>`)}
function s2transition(){panel(`<div class="eyebrow">Dienstag · 18:27 Uhr</div><h2>Geschafft – die Fragen zum Testprozess wurden geklärt.</h2><div class="story">Jetzt kann die konkrete Testanalyse und Testfallerstellung beginnen.</div><button class="primary" onclick="s3intro()">Mittwoch öffnen</button>`)}
function s3intro(){setP(3,'Woche 1 · Mittwoch');panel(`<div class="eyebrow">Mittwoch · 09:18 Uhr</div><h2>Unterstützung bei der Testfallanalyse</h2><div class="story">Die Tester sind dabei, die Anforderungen zu sichten und zu analysieren und daraus Testinhalte abzuleiten. Testfälle werden im Tool erstellt.<br><br>Ein Kollege benötigt dabei Unterstützung. Hier muss unter die Arme gegriffen werden.</div><button class="primary" onclick="s3()">Unterstützung beginnen</button>`)}
function s3(){setP(3,'Woche 1 · Mittwoch');panel(`<div class="eyebrow">Testfallanalyse</div><h2>Das neue Überweisungslimit</h2>${meter(0,'TESTFALLANALYSE UND -ERSTELLUNG')}${anf327()}<button class="primary" onclick="s3classes()">Anforderung analysieren</button>`)}
function s3classes(){picks.clear();let vals=['−500','−1','0','1','500','999','1.000','1.001','5.000','9.999','10.000','10.001','15.000'];panel(`<div class="eyebrow">Testfallanalyse</div><h2>Äquivalenzklassen</h2>${anf327()}<p>Wählt alle Werte der Klasse <b>„zusätzliche Freigabe erforderlich“ (&gt;1.000 bis 10.000 €)</b>.</p><div class="chips">${vals.map((v,i)=>`<button class="chip" id="v${i}" onclick="togglePick('v',${i})">${v} €</button>`).join('')}</div><button onclick="checkClass()">Klasse prüfen</button><div id="fb"></div>`)}
function checkClass(){let right=[7,8,9,10],ok=right.every(i=>picks.has('v'+i))&&picks.size===4;document.querySelector('#fb').innerHTML=ok?msg('✓ ÄQUIVALENZKLASSE KORREKT',true)+award('s3class',5)+meter(35,'TESTFALLANALYSE UND -ERSTELLUNG')+`<button class="primary" onclick="s3representatives()">Vertreter auswählen</button>`:msg('Prüft noch einmal die Grenzen der Klasse in ANF-327.')}
function s3representatives(){let all=`<option value="" selected disabled>– Wert auswählen –</option><option value="−500">−500</option><option value="−1">−1</option><option value="0">0</option><option value="1">1</option><option value="500">500</option><option value="999">999</option><option value="1.000">1.000</option><option value="1.001">1.001</option><option value="5.000">5.000</option><option value="9.999">9.999</option><option value="10.000">10.000</option><option value="10.001">10.001</option><option value="15.000">15.000</option>`;panel(`<div class="eyebrow">Testfallanalyse</div><h2>Äquivalenzklassen</h2>${anf327()}<p>Für eine erste Abdeckung genügt jeweils ein repräsentativer Wert. Mehrere Lösungen sind möglich.</p><div class="grid4">${['A &lt; 0 €','B 0–1.000 €','C &gt;1.000–10.000 €','D &gt;10.000 €'].map((x,i)=>`<div class="bucket">${x}<br><select id="e${i+1}" autocomplete="off">${all}</select></div>`).join('')}</div><button onclick="checkRepresentatives()">Vertreter übernehmen</button><div id="fb"></div>`);['e1','e2','e3','e4'].forEach(id=>{const el=document.getElementById(id);if(el){el.selectedIndex=0;el.value='';}})}
function checkRepresentatives(){let a=[e1.value,e2.value,e3.value,e4.value], ok=a[0]&&a[1]&&a[2]&&a[3]&&['−500','−1'].includes(a[0])&&['0','1','500','999','1.000'].includes(a[1])&&['1.001','5.000','9.999','10.000'].includes(a[2])&&['10.001','15.000'].includes(a[3]);document.querySelector('#fb').innerHTML=ok?msg('✓ Für jede Äquivalenzklasse wurde ein passender Vertreter gewählt.',true)+award('s3rep',5)+`<button class="primary" onclick="s3thursday()">Weiter</button>`:msg('Mindestens ein Wert gehört nicht zur gewählten Äquivalenzklasse.')}
function s3thursday(){panel(`<div class="eyebrow">Mittwoch · Feierabend</div><div class="sleepcard"><div class="sleepart" aria-hidden="true">🌙<br><span>😴</span> 🛏️</div><h2>Feierabend</h2><p>Für heute ist genug analysiert. Die restliche Testfallanalyse geht morgen weiter.</p><div class="mono">… einige Stunden später …</div></div><button class="primary" onclick="s3thursdayStart()">Donnerstag starten</button>`)}
function s3thursdayStart(){setP(3,'Woche 1 · Donnerstag');panel(`<div class="eyebrow">Testfallanalyse</div><h2>Grenzwertanalyse</h2>${anf327()}<div class="story">Die Äquivalenzklassen stehen. Jetzt werden die Grenzwertübergänge betrachtet.</div><button class="primary" onclick="s3bounds()">Grenzwerte prüfen</button>`)}
function s3bounds(){panel(`<div class="eyebrow">Testfallanalyse</div><h2>Grenzwertübergänge</h2>${anf327()}<p>An drei Stellen ändert sich das erwartete Verhalten. Welche drei Paare liegen direkt an diesen Grenzen?</p><div class="options"><button id="b1" onclick="bound(false,'b1')">0/1 · 999/1.000 · 9.999/10.000</button><button id="b2" onclick="bound(true,'b2')">−1/0 · 1.000/1.001 · 10.000/10.001</button><button id="b3" onclick="bound(false,'b3')">−500/0 · 500/5.000 · 10.000/15.000</button></div><div id="fb"></div>`)}
function bound(ok,id){document.querySelectorAll('.options button').forEach(b=>b.classList.remove('selected'));document.querySelector('#'+id).classList.add('selected');document.querySelector('#fb').innerHTML=ok?msg('✓ GRENZWERTÜBERGÄNGE KORREKT',true)+award('s3bound',5)+meter(70,'TESTFALLANALYSE UND -ERSTELLUNG')+`<button class="primary" onclick="s3data()">Testfälle erstellen</button>`:msg('Diese Werte liegen nicht jeweils direkt auf beiden Seiten der drei relevanten Grenzen.')}
function s3data(){panel(`<div class="eyebrow">Testfallerstellung</div><h2>Testfälle erstellen</h2>${anf327()}<table><tr><th>Testfall</th><th>Wert</th><th>Erwartetes Ergebnis</th></tr><tr><td>TF-327-01</td><td>−1 €</td><td>Eingabe abgelehnt</td></tr><tr><td>TF-327-02</td><td>0 €</td><td>Keine zusätzliche Freigabe</td></tr><tr><td>TF-327-03</td><td>1.000 €</td><td>Keine zusätzliche Freigabe</td></tr><tr><td>TF-327-04</td><td>1.001 €</td><td>Zusätzliche Freigabe erforderlich</td></tr><tr><td>TF-327-05</td><td>10.000 €</td><td>Zusätzliche Freigabe erforderlich</td></tr><tr><td>TF-327-06</td><td>10.001 €</td><td>Eingabe abgelehnt</td></tr></table>${meter(100,'TESTFALLANALYSE UND -ERSTELLUNG')}<div class="notice good">6 Testfälle wurden für das Thema Überweisungslimit erstellt. Weitere 234 wurden für die anderen Bereiche erstellt.<br><b>Status: Testanalyse und Testentwurf abgeschlossen.</b></div><button class="primary" onclick="finishCases()">Woche 1 abschließen</button>`)}
function finishCases(){let bonus=award('s3cases',5);week1end(bonus)}
function week1end(bonus=''){setP(3,'Woche 1 · Freitag');panel(`${bonus}<div class="eyebrow">Freitag · 16:42 Uhr</div><h2>BEREIT FÜR DIE TESTDURCHFÜHRUNG</h2><div class="notice good"><b>Die Vorbereitungen für die kommende Woche sind abgeschlossen:</b><br><br>✓ Testplanung wurde wiederhergestellt<br>✓ Ressourcen für Woche 2 wurden bestätigt<br>✓ Release 2.0 steht auf der Zentralen Testumgebung bereit<br>✓ Testanalyse und Testfallerstellung sind abgeschlossen</div><div class="notice good"><b>WOCHE 1 · QS ABGESCHLOSSEN</b><br>Dieser getrennte QS-Stand endet hier. Woche 2 wird in einer eigenen Version geprüft.</div>`)}

start();
