const app=document.querySelector('#app'), prog=document.querySelector('#progress'), creditEl=document.querySelector('#credits');
let credits=0; const awarded=new Set(); let currentClock='';
function setClock(t){currentClock=t;}
function updateCredits(){if(creditEl) creditEl.textContent=`CREDITS ${credits} / 100`;}
function award(key,n){if(!awarded.has(key)){awarded.add(key);credits=Math.min(100,credits+n);updateCredits();return `<div class=\"creditpop\">+${n} CREDITS</div>`}return '';}
function resetCredits(){credits=0;awarded.clear();updateCredits();}
const panel=html=>{app.innerHTML=`<section class="panel">${currentClock?`<div class="eyebrow globalclock">${currentClock}</div>`:''}${html}</section>`;scrollTo({top:0,behavior:'smooth'})};
const setP=(n,label='')=>prog.textContent=n?`Station ${n} / 7${label?' · '+label:''}`:'Start';
const msg=(t,g=false)=>`<div class="notice ${g?'good':'bad'}">${t}</div>`;
const meter=(n,label)=>`<div class="statusline"><b>${label}</b><span>${n} %</span></div><div class="bar"><i style="width:${n}%"></i></div>`;
const anf327=()=>`<div class="req stickyreq"><b>ANF-327 – Persönliches Überweisungslimit</b><br>0–1.000 € einschließlich: ohne zusätzliche Freigabe<br>&gt;1.000–10.000 € einschließlich: zusätzliche Freigabe erforderlich<br>&gt;10.000 €: unzulässig<br>Negative Werte: unzulässig<br>Nur ganze Eurobeträge.</div>`;
let picks=new Set();
function start(){currentClock='';resetCredits();setP(0);panel(`<div class="eyebrow">Test-Escape-Spiel</div><h1>Release 2.0</h1><h2>Release in Gefahr</h2><div class="story"><b>Montag, 08:12 Uhr.</b><br><br>In zwei Wochen soll das neue Release des Kundenportals unseres Finanzinstituts live gehen. Aber in unserem Release-Projekt haben sich einige Fehler eingeschlichen und so können wir nicht live gehen.<br><br><b>Die Aufgabe:</b> Die aufgetretenen Probleme lösen und Release 2.0 wieder auf Kurs bringen.<br><br>Dabei können auch unvorhergesehene Dinge passieren. Dann sind passende Lösungen gefragt.<br><br><b>Bereit für die Herausforderung?</b></div><button class="primary" onclick="boot()">Release retten</button>`)}
function boot(){panel(`<div class="eyebrow">Release 2.0</div><h2>TESTLEITSTAND</h2><div class="story mono">SYSTEMSTART …<br>PROJEKTDATEN WERDEN GELADEN …<br><br><span class="badtext">⚠ FEHLER BEIM LADEN</span><br><br>Testplanung für Release 2.0 unvollständig.</div><button class="primary" onclick="s1()">Testkonzept öffnen</button>`)}
function s1(){setP(1,'Woche 1 · Montag');panel(`<div class="eyebrow">Station 1 · Montag 08:12 Uhr</div><h2>Der Auftrag – Testkonzept vervollständigen</h2>${meter(43,'STAND TESTKONZEPT')}<div class="file"><b>TESTKONZEPT – RELEASE 2.0</b><br><br>Testobjekt: Kundenportal – Release 2.0 ✓<br>Testzeitraum: Vorbereitung Woche 1 · Durchführung und Abschluss Woche 2 ✓<br>Testziele: <span class="badtext">DATEN BESCHÄDIGT</span><br>Testumfang: <span class="badtext">DATEN BESCHÄDIGT</span><br>Testumgebung: <span class="badtext">DATEI GELÖSCHT</span><br>Testüberwachung und Teststeuerung: <span class="badtext">DATEN BESCHÄDIGT</span></div><button class="primary" onclick="s1goals()">Testziele prüfen</button>`)}
function s1goals(){picks.clear();let a=['Informationen über die Qualität von Release 2.0 gewinnen.','Nachweisen, dass Release 2.0 vollständig fehlerfrei ist.','Prüfen, ob festgelegte Anforderungen erfüllt sind.','Fehlerzustände und Fehlerwirkungen aufdecken.','Sicherstellen, dass nach Produktivsetzung niemals Fehlerwirkungen auftreten.','Informationen als Grundlage für Entscheidungen bereitstellen.'];panel(`<div class="eyebrow">Station 1 · Testziele</div><h2>Testziele vervollständigen</h2><div class="notice">6 Textfragmente gefunden. <b>4</b> gehören zum Testkonzept.</div><div class="options">${a.map((x,i)=>`<button id="g${i}" onclick="togglePick('g',${i})">${'ABCDEF'[i]}) ${x}</button>`).join('')}</div><button onclick="checkGoals()">Fragmente übernehmen</button><div id="fb"></div>`)}
function togglePick(prefix,i){let k=prefix+i;picks.has(k)?picks.delete(k):picks.add(k);document.querySelector('#'+k).classList.toggle('selected')}
function checkGoals(){let ok=[0,2,3,5].every(i=>picks.has('g'+i))&&picks.size===4;document.querySelector('#fb').innerHTML=ok?msg('✓ DATEN WURDEN KORRIGIERT',true)+meter(57,'STAND TESTKONZEPT')+`<button class="primary" onclick="s1scope()">Testumfang prüfen</button>`:msg('Nicht alle Fragmente passen. Testen kann das Vorhandensein von Fehlerzuständen zeigen, nicht deren vollständige Abwesenheit.')}
function s1scope(){panel(`<div class="eyebrow">Station 1 · Testumfang</div><h2>Testumfang klar?</h2><div class="notice bad">„Für Release 2.0 testen wir nur die neuen Funktionen. Bestehende Funktionen wurden schließlich bereits getestet.“</div><table><tr><th>Bereich</th><th>Änderung</th></tr><tr><td>Persönliches Überweisungslimit</td><td>NEU</td></tr><tr><td>Profilbild</td><td>NEU</td></tr><tr><td>Umsatzsuche</td><td>GEÄNDERT</td></tr><tr><td>Elektronisches Postfach</td><td>GEÄNDERT</td></tr><tr><td>Anmeldung / Kontosperre</td><td>TECHNISCH ÜBERARBEITET</td></tr><tr><td>Persönliche Daten</td><td>TECHNISCH ÜBERARBEITET</td></tr></table><button onclick="scope(false)">Notiz übernehmen</button><button onclick="scope(true)">Notiz als fehlerhaft markieren</button><div id="fb"></div>`)}
function scope(ok){document.querySelector('#fb').innerHTML=ok?msg('✓ DATEN WURDEN KORRIGIERT',true)+`<div class="req">Neue und geänderte Funktionen sowie bestehende Funktionen, die durch Änderungen betroffen sein können, müssen bei der Testplanung berücksichtigt werden.</div>${meter(71,'STAND TESTKONZEPT')}<button class="primary" onclick="s1env()">Testumgebung prüfen</button>`:msg('Die Änderungen können auch bestehende Funktionen beeinflussen.')}
function s1env(){panel(`<div class="eyebrow">Station 1 · Testumgebung</div><h2>testumgebung_release20.cfg</h2><div class="notice bad">⚠ DATEI NICHT GEFUNDEN · 3 Wiederherstellungspunkte erkannt</div><div class="cards"><div class="card"><h4>Anwendungstestumgebung</h4>Release 2.0 bereitstellbar; häufige neue Zustände; nicht alle angebundenen Systeme release-nah.</div><div class="card"><h4>Zentrale Testumgebung</h4>Vorgesehener Stand; benötigte Systeme/Schnittstellen; definierte Testkonten/-daten; kontrollierte Ausgangslage.</div><div class="card"><h4>Entwicklungsumgebung</h4>Aktuelle Komponentenstände; kurzfristige Änderungen; nicht zwingend alle Komponenten gleichzeitig verfügbar.</div></div><div class="req"><b>BENÖTIGT</b><br>✓ vorgesehener Stand von Release 2.0<br>✓ definierte Testdaten und Testkonten<br>✓ benötigte angebundene Systeme und Schnittstellen<br>✓ kontrollierte Ausgangslage</div><div class="options"><button onclick="env(false)">Anwendungstestumgebung wiederherstellen</button><button onclick="env(true)">Zentrale Testumgebung wiederherstellen</button><button onclick="env(false)">Entwicklungsumgebung wiederherstellen</button></div><div id="fb"></div>`)}
function env(ok){document.querySelector('#fb').innerHTML=ok?msg('✓ DATEN WURDEN KORRIGIERT',true)+meter(86,'STAND TESTKONZEPT')+`<button class="primary" onclick="s1control()">Letzten Bereich prüfen</button>`:msg('Diese Umgebung erfüllt die aufgeführten Anforderungen nicht vollständig.')}
function s1control(){panel(`<div class="eyebrow">Station 1 · Testüberwachung und Teststeuerung</div><h2>Beschädigte Regel</h2><div class="notice bad">„Der einmal erstellte Testplan darf während der beiden Wochen nicht mehr verändert werden.“</div><div class="options"><button onclick="control(false)">Regel bestätigen</button><button onclick="control(true)">Regel korrigieren</button></div><div id="fb"></div>`)}
function control(ok){document.querySelector('#fb').innerHTML=ok?msg('✓ DATEN WURDEN KORRIGIERT',true)+`<div class="req">Testfortschritt, Testergebnisse, Fehlermeldungen und verfügbare Ressourcen werden überwacht. Bei relevanten Abweichungen werden geeignete Steuerungsmaßnahmen getroffen und die Planung bei Bedarf angepasst.</div>${meter(100,'STAND TESTKONZEPT')}<button class="primary" onclick="s1end()">Testkonzept abschließen</button>`:msg('Ein Testplan kann bei relevanten Abweichungen angepasst werden.')}
function s1end(){let bonus=award('s1',15);panel(`${bonus}<div class="eyebrow">Station 1 · Abschluss</div><h2>TESTKONZEPT VOLLSTÄNDIG</h2>${meter(100,'STAND TESTKONZEPT')}<div class="notice good"><b>Testziele:</b> wurden wiederhergestellt<br><b>Testumfang:</b> wurde repariert<br><b>Testumgebung:</b> wurde wiederhergestellt<br><b>Testüberwachung und Teststeuerung:</b> wurden wiederhergestellt</div><div class="story mono">ÄNDERUNGEN WERDEN GESPEICHERT …<br>TESTKONZEPT WIRD VALIDIERT …<br><span class="goodtext">✓ ERFOLGREICH</span></div><button class="primary" onclick="s1transition()">Weiter</button>`)}
function s1transition(){panel(`<div class="eyebrow">Woche 1 · Montag abgeschlossen</div><h2>Geschafft – das Testkonzept steht!</h2><div class="story">Doch damit ist Release 2.0 noch lange nicht gerettet. Weitere Herausforderungen warten bereits.<br><br><b>Bereit, weiterzumachen?</b></div><button class="primary" onclick="s2()">Dienstag öffnen</button>`)}
function s2(){setP(2,'Woche 1 · Dienstag');panel(`<div class="eyebrow">Station 2 · Dienstag 08:47 Uhr</div><h2>Das Testprozess-Chaos</h2>${meter(18,'TESTPROZESS KLAR')}<div class="story">Das Testkonzept steht. Bevor wir in die Testanalyse einsteigen können, gibt es noch Rückfragen zum Testprozess.</div><div class="notice bad">Mehrere Testaktivitäten wurden falsch zugeordnet. Eine zentrale Aktivität fehlt vollständig.</div><button class="primary" onclick="s2match()">Testprozess klären</button>`)}
function s2match(){let acts=['Tests in der Zentralen Testumgebung durchführen und tatsächliche mit erwarteten Ergebnissen vergleichen.','Testziele, Testumfang und Ressourcen festlegen.','Ergebnisse zusammenfassen, offene Punkte dokumentieren und den Testabschlussbericht erstellen.','Anforderungen an das persönliche Überweisungslimit untersuchen und testbare Merkmale identifizieren.','Testdaten und Testfälle für die Durchführung vorbereiten und verfügbar machen.','Äquivalenzklassen und Grenzwerte bestimmen und daraus Testfälle ableiten.'];let opts=['','Testplanung','Testanalyse','Testentwurf','Testrealisierung','Testdurchführung','Testabschluss'];panel(`<div class="eyebrow">Station 2 · Dienstag 08:47 Uhr</div><h2>Testaktivitäten zuordnen</h2>${acts.map((a,i)=>`<div class="req"><b>${'ABCDEF'[i]}</b> ${a}<br><select id="m${i}">${opts.map(o=>`<option>${o||'– Aktivität wählen –'}</option>`).join('')}</select></div>`).join('')}<button onclick="checkMatch()">Zuordnung prüfen</button><div id="fb"></div>`)}
function checkMatch(){let exp=['Testdurchführung','Testplanung','Testabschluss','Testanalyse','Testrealisierung','Testentwurf'];let ok=exp.every((x,i)=>document.querySelector('#m'+i).value===x);document.querySelector('#fb').innerHTML=ok?msg('✓ AKTIVITÄTEN ZUGEORDNET',true)+meter(52,'TESTPROZESS KLAR')+`<button class="primary" onclick="s2missing()">Fehlende Aktivität suchen</button>`:msg('Mindestens eine Tätigkeit passt nicht zur gewählten Testaktivität.')}
function s2missing(){panel(`<div class="eyebrow">Station 2 · Dienstag 08:47 Uhr</div><h2>Eine Aktivität fehlt</h2><div class="timeline"><div>Testplanung</div><div>↓ Testanalyse</div><div>↓ Testentwurf</div><div>↓ Testrealisierung</div><div>↓ Testdurchführung</div><div>↓ Testabschluss</div></div><div class="notice bad">⚠ Eine zentrale Aktivität fehlt.</div><div class="cards"><button onclick="missing(false)">release_notes.txt</button><button onclick="missing(true)">prozess_alt.tmp</button><button onclick="missing(false)">meeting_montag.old</button><button onclick="missing(false)">portal_logo.bak</button></div><div id="fb"></div>`)}
function missing(ok){document.querySelector('#fb').innerHTML=ok?msg('✓ TESTÜBERWACHUNG UND TESTSTEUERUNG GEFUNDEN',true)+`<p>Wo gehört diese Aktivität hin?</p><div class="options"><button onclick="place(false)">Zwischen Testplanung und Testanalyse</button><button onclick="place(true)">Begleitend zu den Testaktivitäten</button><button onclick="place(false)">Erst nach dem Testabschluss</button></div><div id="placefb"></div>`:msg('Diese Datei enthält keine fehlende Testaktivität.')}
function place(ok){document.querySelector('#placefb').innerHTML=ok?msg('✓ TESTÜBERWACHUNG UND TESTSTEUERUNG RICHTIG EINGEORDNET',true)+meter(81,'TESTPROZESS KLAR')+`<div class="req"><b>Begleitende Aktivität:</b> Testfortschritt und relevante Abweichungen werden während der Testaktivitäten überwacht. Bei Bedarf werden Steuerungsmaßnahmen eingeleitet.</div><button class="primary" onclick="s2end()">Testprozess abschließen</button>`:msg('Testüberwachung und Teststeuerung begleiten die Testaktivitäten und gehören nicht nur an einen einzelnen Punkt.')}
function s2end(){panel(`<div class="eyebrow">Station 2 · Abschluss</div><h2>Fragen zum Testprozess geklärt</h2>${meter(100,'TESTPROZESS KLAR')}<div class="notice good">✓ Testplanung<br>✓ Testanalyse<br>✓ Testentwurf<br>✓ Testrealisierung<br>✓ Testdurchführung<br>✓ Testabschluss<br>✓ Testüberwachung und Teststeuerung begleitend</div><button class="primary" onclick="s2transition()">Weiter</button>`)}
function s2transition(){let bonus=award('s2',10);panel(`${bonus}<div class="eyebrow">Woche 1 · Dienstag abgeschlossen</div><h2>Geschafft – die Fragen zum Testprozess wurden geklärt.</h2><div class="story">Jetzt kann die konkrete Testanalyse und Testfallerstellung beginnen.</div><button class="primary" onclick="s3()">Mittwoch öffnen</button>`)}
function s3(){setP(3,'Woche 1 · Mittwoch');panel(`<div class="eyebrow">Station 3 · Mittwoch 09:18 Uhr</div><h2>Das neue Überweisungslimit</h2>${meter(0,'TESTFALLANALYSE UND -ERSTELLUNG')}<div class="notice bad">⚠ TESTFÄLLE NOCH NICHT ERSTELLT</div>${anf327()}<button class="primary" onclick="s3classes()">Anforderung analysieren</button>`)}
function s3classes(){picks.clear();let vals=['−500','−1','0','1','500','999','1.000','1.001','5.000','9.999','10.000','10.001','15.000'];panel(`<div class="eyebrow">Station 3 · Mittwoch 09:18 Uhr</div><h2>Äquivalenzklassen klar</h2>${anf327()}<p>Wählt alle Werte der Klasse <b>„zusätzliche Freigabe erforderlich“ (&gt;1.000 bis 10.000 €)</b>.</p><div class="chips">${vals.map((v,i)=>`<button class="chip" id="v${i}" onclick="togglePick('v',${i})">${v} €</button>`).join('')}</div><button onclick="checkClass()">Klasse prüfen</button><div id="fb"></div>`)}
function checkClass(){let right=[7,8,9,10],ok=right.every(i=>picks.has('v'+i))&&picks.size===4;document.querySelector('#fb').innerHTML=ok?msg('✓ ÄQUIVALENZKLASSE KORREKT',true)+meter(35,'TESTFALLANALYSE UND -ERSTELLUNG')+`<button class="primary" onclick="s3representatives()">Vertreter auswählen</button>`:msg('Prüft noch einmal die Grenzen der Klasse in ANF-327.')}
function s3representatives(){let all=`<option value="" selected disabled>– Wert auswählen –</option><option value="−500">−500</option><option value="−1">−1</option><option value="0">0</option><option value="1">1</option><option value="500">500</option><option value="999">999</option><option value="1.000">1.000</option><option value="1.001">1.001</option><option value="5.000">5.000</option><option value="9.999">9.999</option><option value="10.000">10.000</option><option value="10.001">10.001</option><option value="15.000">15.000</option>`;panel(`<div class="eyebrow">Station 3 · Mittwoch 09:18 Uhr</div><h2>Äquivalenzklassen klar</h2>${anf327()}<p>Für eine erste Abdeckung genügt jeweils ein repräsentativer Wert. Mehrere Lösungen sind möglich.</p><div class="grid4">${['A &lt; 0 €','B 0–1.000 €','C &gt;1.000–10.000 €','D &gt;10.000 €'].map((x,i)=>`<div class="bucket">${x}<br><select id="e${i+1}" autocomplete="off">${all}</select></div>`).join('')}</div><button onclick="checkRepresentatives()">Vertreter übernehmen</button><div id="fb"></div>`);['e1','e2','e3','e4'].forEach(id=>{const el=document.getElementById(id);if(el){el.selectedIndex=0;el.value='';}})}
function checkRepresentatives(){let a=[e1.value,e2.value,e3.value,e4.value], ok=a[0]&&a[1]&&a[2]&&a[3]&&['−500','−1'].includes(a[0])&&['0','1','500','999','1.000'].includes(a[1])&&['1.001','5.000','9.999','10.000'].includes(a[2])&&['10.001','15.000'].includes(a[3]);document.querySelector('#fb').innerHTML=ok?msg('✓ Für jede Äquivalenzklasse wurde ein passender Vertreter gewählt.',true)+`<button class="primary" onclick="s3thursday()">Weiter</button>`:msg('Mindestens ein Wert gehört nicht zur gewählten Äquivalenzklasse.')}
function s3thursday(){panel(`<div class="eyebrow">Station 3 · Donnerstag 09:18 Uhr</div><h2>Grenzwertanalyse</h2>${anf327()}<div class="story">Die Äquivalenzklassen stehen. Jetzt werden die Grenzwertübergänge betrachtet.</div><button class="primary" onclick="s3bounds()">Grenzwerte prüfen</button>`)}
function s3bounds(){panel(`<div class="eyebrow">Station 3 · Donnerstag 09:18 Uhr</div><h2>Grenzwertübergänge</h2>${anf327()}<p>An drei Stellen ändert sich das erwartete Verhalten. Welche drei Paare liegen direkt an diesen Grenzen?</p><div class="options"><button id="b1" onclick="bound(false,'b1')">0/1 · 999/1.000 · 9.999/10.000</button><button id="b2" onclick="bound(true,'b2')">−1/0 · 1.000/1.001 · 10.000/10.001</button><button id="b3" onclick="bound(false,'b3')">−500/0 · 500/5.000 · 10.000/15.000</button></div><div id="fb"></div>`)}
function bound(ok,id){document.querySelectorAll('.options button').forEach(b=>b.classList.remove('selected'));document.querySelector('#'+id).classList.add('selected');document.querySelector('#fb').innerHTML=ok?msg('✓ GRENZWERTÜBERGÄNGE KORREKT',true)+meter(70,'TESTFALLANALYSE UND -ERSTELLUNG')+`<button class="primary" onclick="s3data()">Testfälle erstellen</button>`:msg('Diese Werte liegen nicht jeweils direkt auf beiden Seiten der drei relevanten Grenzen.')}
function s3data(){panel(`<div class="eyebrow">Station 3 · Donnerstag 09:18 Uhr</div><h2>Testfälle erstellen</h2>${anf327()}<table><tr><th>Testfall</th><th>Wert</th><th>Erwartetes Ergebnis</th></tr><tr><td>TF-327-01</td><td>−1 €</td><td>Eingabe abgelehnt</td></tr><tr><td>TF-327-02</td><td>0 €</td><td>Keine zusätzliche Freigabe</td></tr><tr><td>TF-327-03</td><td>1.000 €</td><td>Keine zusätzliche Freigabe</td></tr><tr><td>TF-327-04</td><td>1.001 €</td><td>Zusätzliche Freigabe erforderlich</td></tr><tr><td>TF-327-05</td><td>10.000 €</td><td>Zusätzliche Freigabe erforderlich</td></tr><tr><td>TF-327-06</td><td>10.001 €</td><td>Eingabe abgelehnt</td></tr></table>${meter(100,'TESTFALLANALYSE UND -ERSTELLUNG')}<div class="notice good">6 Testfälle wurden erstellt.<br><b>Status: Testanalyse und Testentwurf abgeschlossen.</b></div><button class="primary" onclick="week1end()">Woche 1 abschließen</button>`)}
function week1end(){let bonus=award('s3',15);panel(`${bonus}<div class="eyebrow">Woche 1 · Freitag 16:42 Uhr</div><h2>BEREIT FÜR DIE TESTDURCHFÜHRUNG</h2><div class="notice good">✓ Testziele definiert<br>✓ Testumfang festgelegt<br>✓ Testanalyse und Testentwurf abgeschlossen</div><div class="story">Die Vorbereitung für Woche 2 ist abgeschlossen.</div><button class="primary" onclick="week2()">Beginn Woche 2</button>`)}
function week2(){setClock('Woche 2 · Montag 08:04 Uhr');panel(`<div class="eyebrow">Woche 2 · Montag 08:04 Uhr</div><h2>START DER TESTDURCHFÜHRUNG</h2><div class="notice bad"><b>⚠ MELDUNG DES UMGEBUNGSMANAGEMENTS</b><br><br>Die Zentrale Testumgebung für Release 2.0 wurde vor Beginn der Testdurchführung geprüft. Dabei wurde ein <b>abgelaufenes SSL-Zertifikat</b> festgestellt.<br><br><b>Gute Nachricht:</b> Die vorgesehene Releasekonfiguration ist bereits installiert.<br><b>Schlechte Nachricht:</b> Das Zertifikat kann aktuell nicht erneuert werden. Der zuständige Kollege ist nicht erreichbar; die Dauer ist unklar.</div><button class="primary" onclick="sslActions()">Situation bewerten</button>`) }
function sslActions(){picks.clear();let a=['Auswirkung auf die geplante Testdurchführung prüfen.','SSL-Zertifikatsprüfung umgehen und normal weitertesten.','Prüfen, welche geplanten Tätigkeiten trotz der Einschränkung sinnvoll durchgeführt werden können.','Release 2.0 aufgrund des Zertifikats sofort absagen.','Umgebungsmanagement kontaktieren und Klärung bzw. Wiederherstellung anstoßen.','Einfach warten und bis zur Behebung keinerlei weitere Aktivitäten durchführen.','Abweichung dokumentieren und Planung bei Bedarf anpassen.','Die verlorene Testzeit später als durchgeführte Testzeit dokumentieren.'];panel(`<div class="eyebrow">Woche 2 · Planabweichung</div><h2>Wie soll auf die Störung reagiert werden?</h2><p><b>Bis zu vier Maßnahmen auswählen.</b> Die erste bestätigte Entscheidung zählt für die Credits.</p><div class="options">${a.map((x,i)=>`<button id="ssl${i}" onclick="sslPick(${i})">${i+1}. ${x}</button>`).join('')}</div><button onclick="checkSSL()">Maßnahmen bestätigen</button><div id="fb"></div>`) }
function sslPick(i){let k='ssl'+i;if(picks.has(k)){picks.delete(k);document.getElementById(k).classList.remove('selected')}else if(picks.size<4){picks.add(k);document.getElementById(k).classList.add('selected')}}
function checkSSL(){
 if(!picks.size){document.querySelector('#fb').innerHTML=msg('Mindestens eine Maßnahme auswählen.');return}
 let goodIds=[0,2,4,6], badIds=[1,3,5,7];
 let good=goodIds.filter(i=>picks.has('ssl'+i)).length;
 let bad=badIds.filter(i=>picks.has('ssl'+i));
 if(bad.length){
   const questions={
    1:'Ist es für eine kontrollierte Testdurchführung sinnvoll, eine festgestellte Sicherheitsprüfung der vorgesehenen Testumgebung zu umgehen?',
    3:'Reicht die vorliegende Störung bereits aus, um eine Entscheidung über das gesamte Release zu treffen?',
    5:'Werden die vorhandenen Handlungsmöglichkeiten ausreichend genutzt, wenn ausschließlich auf die Behebung gewartet wird?',
    7:'Darf nicht durchgeführte Testzeit als tatsächlich durchgeführte Testaktivität dokumentiert werden?'
   };
   document.querySelector('#fb').innerHTML=`<div class="notice bad"><b>Ausgewählte Maßnahmen noch einmal kritisch betrachten:</b><ul>${bad.map(i=>`<li>${questions[i]}</li>`).join('')}</ul><br>Ungeeignete Maßnahmen können wieder abgewählt und durch andere Maßnahmen ersetzt werden.</div>`;
   return;
 }
 let score=Math.round(good*2.5), bonus=award('ssl',score);
 let summary=good===4?msg('Die Auswahl berücksichtigt die wesentlichen Handlungsmöglichkeiten der Planabweichung.',true):msg('Es wären noch weitere sinnvolle Maßnahmen auswählbar gewesen. Der gewählte Weg ist dennoch möglich. Schauen wir, welches Update das Umgebungsmanagement inzwischen hat.',true);
 document.querySelector('#fb').innerHTML=summary+bonus+`<button class="primary" onclick="sslUpdate()">Update des Umgebungsmanagements öffnen</button>`;
 document.querySelectorAll('#app .options button, #app button:not(.primary)').forEach(b=>b.disabled=true);
}

function sslUpdate(){setClock('Woche 2 · Montag 09:26 Uhr');panel(`<div class="eyebrow">Woche 2 · Montag 09:26 Uhr</div><h2>UPDATE UMGEBUNGSMANAGEMENT</h2><div class="notice good">✓ Das SSL-Zertifikat wurde erneuert.<br>✓ Die Zentrale Testumgebung ist wieder verfügbar.<br>✓ Die Verzögerung wurde als Planabweichung dokumentiert.</div><div class="story">Die Testdurchführung kann nun beginnen.</div><button class="primary" onclick="s4()">Testdurchführung starten</button>`) }
function s4(){setClock('Woche 2 · Montag 10:17 Uhr');setP(4,'Woche 2 · Montag');panel(`<h2>Der gesperrte Zugang</h2><div class="story">Ein Tester/Testanalyst kommt mit einem Anliegen. Bei einem Test des Logins im Kundenportal wurde ein Verhalten beobachtet, das nicht korrekt erscheint. Kann bei der Einordnung unterstützt werden?</div><div class="req"><b>ANF-042 – Login im Kundenportal</b><br>Nach drei aufeinanderfolgenden falschen Passworteingaben muss das Benutzerkonto für <b>15 Minuten</b> gesperrt werden.</div><div class="story"><b>Folgende Tests wurden durchgeführt:</b><br><br>Schritt 1 – Falsches Passwort → Anmeldung abgelehnt ✓<br>Schritt 2 – Falsches Passwort → Anmeldung abgelehnt ✓<br>Schritt 3 – Falsches Passwort → „Benutzerkonto gesperrt“ ✓<br>Schritt 4 – Browser aktualisiert<br>Schritt 5 – Korrektes Passwort → <b class="badtext">Anmeldung erfolgreich</b></div><h3>Welche Aussage ist durch die Beobachtung gestützt?</h3><div class="options"><button onclick="s4a(false)">Die Sperrinformation wurde nachweislich ausschließlich im Browser gespeichert.</button><button onclick="s4a(true)">Im Testobjekt befindet sich ein Fehlerzustand. Bei der Testdurchführung zeigt sich eine Fehlerwirkung.</button><button onclick="s4a(false)">Die konkrete Fehlhandlung in der Entwicklung ist damit nachgewiesen.</button></div><div id="fb"></div>`) }

function s4a(ok){document.querySelector('#fb').innerHTML=ok?msg('✓ Korrekt – Der Tester/Testanalyst hat eine Fehlerwirkung entdeckt. Diese muss nun über eine Fehlermeldung an die Entwicklung weitergegeben werden.',true)+`<button class="primary" onclick="s4ideas()">Weiter</button>`:msg('Aus der sichtbaren Fehlerwirkung lässt sich keine konkrete Fehlhandlung sicher ableiten.')}

function s4ideas(){picks.clear();let a=['Schriftgröße der Fehlermeldung überprüfen','Sperre nach Schließen und erneutem Öffnen des Browsers prüfen','Profilbild ändern','Anmeldung nach Ablauf der 15 Minuten prüfen','Rechtschreibung im Impressum prüfen','Sperre in einer zweiten Sitzung prüfen','Farbe der Schaltfläche „Anmelden“ prüfen','Anmeldung unmittelbar vor Ablauf der Sperrzeit prüfen'];panel(`<h2>Weitere Testfälle</h2><div class="story">Welche weiteren Tests könnten zur Untersuchung des beobachteten Verhaltens sinnvoll sein?</div><div class="req"><b>ANF-042 – Login im Kundenportal</b><br>Nach drei aufeinanderfolgenden falschen Passworteingaben muss das Benutzerkonto für 15 Minuten gesperrt werden.</div><div class="options">${a.map((x,i)=>`<button id="i${i}" onclick="togglePick('i',${i})">${i+1}. ${x}</button>`).join('')}</div><button onclick="checkIdeas()">Auswahl prüfen</button><div id="fb"></div>`) }

function checkIdeas(){let need=[1,3,5,7],good=need.filter(i=>picks.has('i'+i)).length,bad=[0,2,4,6].filter(i=>picks.has('i'+i)).length;if(good>=2&&bad===0){let c=good===4?5:3;document.querySelector('#fb').innerHTML=award('s4ideas',c)+msg(good===4?'✓ Richtig – die relevanten weiteren Testfälle wurden erkannt.':'✓ Richtig – weitere sinnvolle Testfälle wären möglich gewesen.',true)+`<h3>Abweichungsarchiv gesperrt</h3><p class="small">Hinweis: Der grenzwertnahe Testzeitpunkt unmittelbar vor Ablauf der 15-Minuten-Sperre lautet <b>14:59 Uhr</b>. Dieser Zeitpunkt öffnet das Archiv.</p><input id="c1459" class="code" maxlength="4" inputmode="numeric"><button onclick="code1459()">Öffnen</button><div id="lock"></div>`}else document.querySelector('#fb').innerHTML=msg('Die ausgewählten Testfälle sollten sich unmittelbar auf Dauer und Beständigkeit der Kontosperre beziehen.')}

function time(ok){document.querySelector('#fb').innerHTML=ok?msg('✓ GRENZWERTNAHER TESTZEITPUNKT FESTGELEGT · Erwartung bei 14:59: weiterhin gesperrt.',true)+`<h3>Abweichungsarchiv gesperrt</h3><p class="small">Der letzte festgelegte Testzeitpunkt öffnet das Archiv.</p><input id="c1459" class="code" maxlength="4" inputmode="numeric"><button onclick="code1459()">Öffnen</button><div id="lock"></div>`:msg('Gesucht ist der Zeitpunkt unmittelbar vor Ablauf der 15 Minuten.')}
function code1459(){document.querySelector('#lock').innerHTML=c1459.value==='1459'?award('s4',10)+msg('🔓 PRÜFCODE 1459 AKZEPTIERT · ANF-042: ABWEICHUNG FESTGESTELLT',true)+`<button class="primary" onclick="s5()">Dienstag öffnen</button>`:msg(c1459.value==='2468'?'Die Nummern der Testideen sind nicht entscheidend. Hinweis: Wo ändert sich das erwartete Verhalten?':'Zugriff verweigert. Prüfe den letzten festgelegten Testzeitpunkt.')}
function s5(){setClock('Woche 2 · Dienstag 09:08 Uhr');setP(5,'Woche 2 · Dienstag');panel(`<h2>Fehlermeldung</h2><div class="mail"><b>VON:</b> Entwicklung<br><b>BETREFF:</b> FM-481 – Überweisungsvorlage kann nicht gespeichert werden<br><br>„Nicht nachvollziehbar. Die Vorlage konnte im Test erfolgreich angelegt werden. Welche Daten wurden eingegeben?“</div><div class="notice bad">⚠ FM-481 · INFORMATIONEN UNVOLLSTÄNDIG</div><button class="primary" onclick="s5report()">Fehlermeldung prüfen</button>`) }

function s5report(){picks.clear();panel(`<h2>FM-481 – Überweisungsvorlage kann nicht gespeichert werden</h2><div class="file"><b>Testdatum:</b> Dienstag, Woche 2<br><br><b>Schritte</b><br>1. Überweisungen öffnen · 2. „Neue Vorlage“ · 3. Daten eingeben · 4. „Speichern“<br><br><b>Erwartet:</b> Vorlage wird gespeichert.<br><b>Tatsächlich:</b> „Die eingegebenen Daten konnten nicht verarbeitet werden.“</div><h3>Welche zwei Informationen helfen hier besonders bei Analyse und Reproduktion?</h3><div class="options"><button id="f0" onclick="togglePick('f',0)">Name der testenden Person</button><button id="f1" onclick="togglePick('f',1)">Verwendete Eingabedaten</button><button id="f2" onclick="togglePick('f',2)">Bildschirmfotos der Testdurchführung</button><button id="f3" onclick="togglePick('f',3)">Farbe der Schaltfläche</button><button id="f4" onclick="togglePick('f',4)">Vermutung zum fehlerhaften Programmcode</button></div><button onclick="checkReport()">Weiter</button><div id="fb"></div>`) }

function checkReport(){let ok=picks.has('f1')&&picks.has('f2')&&picks.size===2;document.querySelector('#fb').innerHTML=ok?msg('✓ FEHLERMELDUNG ERGÄNZT',true)+`<button class="primary" onclick="s5shot()">Weiter</button>`:msg('Gesucht sind Informationen, mit denen die dokumentierte Situation möglichst genau nachvollzogen werden kann.')}

function s5shot(){panel(`<h2>Bildschirmfoto der Testdurchführung</h2><div class="story">Kann erkannt werden, warum es nicht funktioniert hat? Das Bildschirmfoto genau betrachten.</div><div class="screen"><b>Neue Überweisungsvorlage</b><br><br>Empfänger<input value="Müller & Söhne GmbH" readonly>IBAN<input value="DE12 3456 7890 1234 5678 00" readonly>Vorlagenname / Verwendungszweck<input value="Büromiete September" readonly><div class="error">Die eingegebenen Daten konnten nicht verarbeitet werden.</div><p class="small" style="text-align:right">Uhrzeit: <b>17:27</b></p></div><h3>Wie sollte die Situation zunächst reproduziert werden?</h3><div class="options"><button onclick="repro(true)">Mit exakt den dokumentierten Eingabedaten</button><button onclick="repro(false)">Mit beliebigen gültigen Testdaten</button><button onclick="repro(false)">Nur den Empfängernamen ändern</button></div><div id="fb"></div>`) }

function repro(ok){document.querySelector('#fb').innerHTML=ok?msg('✓ REPRODUKTION ERFOLGREICH · Mit den dokumentierten Daten tritt die Fehlerwirkung erneut auf.',true)+`<button class="primary" onclick="s5chars()">Eingabedaten untersuchen</button>`:msg('Zunächst sollten die dokumentierten Bedingungen möglichst genau nachgestellt werden.')}
function s5chars(){panel(`<h2>Zulässige Zeichen – Empfängername</h2><div class="req">Erlaubt: A–Z · a–z · 0–9 · Leerzeichen · . , - / &</div><div class="screen"><b>Neue Überweisungsvorlage</b><br><br>Empfänger<input value="Müller & Söhne GmbH" readonly>IBAN<input value="DE12 3456 7890 1234 5678 00" readonly>Vorlagenname / Verwendungszweck<input value="Büromiete September" readonly><div class="error">Die eingegebenen Daten konnten nicht verarbeitet werden.</div><p class="small" style="text-align:right">Uhrzeit: <b>17:27</b></p></div><h3>Warum hat die Überweisung nicht geklappt?</h3><div class="options"><button onclick="chars(false)">Das Zeichen & ist nicht zulässig.</button><button onclick="chars(true)">Der Empfängername enthält Umlaute.</button><button onclick="chars(false)">Alle verwendeten Zeichen sind laut Vorgabe zulässig.</button></div><div id="fb"></div>`) }

function chars(ok){document.querySelector('#fb').innerHTML=ok?msg('✓ Analyse abgeschlossen – es handelt sich nicht um eine Fehlerwirkung. Das System hat gemäß Vorgabe reagiert. Die Eingabe entsprach nicht den zulässigen Zeichen für den Empfängernamen.',true)+`<div class="req"><b>Ergebnis</b><br>Müller & Söhne GmbH → Eingabe wird abgewiesen<br>Mueller & Soehne GmbH → Vorlage erfolgreich gespeichert</div><h3>Anhangsarchiv gesperrt</h3><p class="small">Die Uhrzeit des Bildschirmfotos öffnet den Zugang.</p><input id="c1727" class="code" maxlength="4" inputmode="numeric"><button onclick="code1727()">Öffnen</button><div id="lock"></div>`:msg('Die zulässigen Zeichen mit dem Empfängernamen im Bildschirmfoto vergleichen.')}

function code1727(){document.querySelector('#lock').innerHTML=c1727.value==='1727'?msg('🔓 1727 AKZEPTIERT · FM-481 ANALYSIERT',true)+`<button class="primary" onclick="s6()">Donnerstag öffnen</button>`:msg('Code nicht akzeptiert. Die Uhrzeit im Bildschirmfoto prüfen.')}

function s6(){setClock('Woche 2 · Donnerstag 13:15 Uhr');award('s5',10);setP(6,'Woche 2 · Donnerstag');panel(`<h2>Die letzten 12 Stunden</h2><div class="story">Es sind nur noch wenige Stunden bis zum Testende. Einige Tests müssen noch durchgeführt werden. Es verbleiben <b>12 Stunden</b> Testkapazität und <b>5 Themengebiete</b> müssen betrachtet werden.<br><br>Es muss abgewogen werden, was noch getestet werden kann und was nicht. Eine Grundlage dafür ist das <b>Produktrisiko</b>.<br><br><b>Doch was ist das?</b></div><div class="req"><b>PRODUKTRISIKO</b><br>[ ? ] × [ ? ]</div><div class="options"><button onclick="risk(false)">Testfallanzahl × Entwicklungsdauer</button><button onclick="risk(false)">Testeranzahl × Testdauer</button><button onclick="risk(true)">Eintrittswahrscheinlichkeit × Schadensausmaß</button><button onclick="risk(false)">Anzahl Änderungen × Anzahl Testfälle</button></div><div id="fb"></div>`) }

function risk(ok){document.querySelector('#fb').innerHTML=ok?msg('✓ Korrekt – Wie wahrscheinlich ist der Eintritt und welches Schadensausmaß entsteht, wenn das Risiko eintritt?',true)+`<button class="primary" onclick="s6matrix()">Weiter</button>`:msg('Produktrisiko betrachtet die Wahrscheinlichkeit und das mögliche Schadensausmaß.')}

function s6matrix(){panel(`<h2>Risikobewertung</h2><div class="cards"><div class="card"><h4>Überweisungen</h4>Hoher Änderungsumfang; falsche Beträge/Empfänger/Freigaben möglich.<br><br><b>TF-327-04</b>: 1.001 € – fehlgeschlagen.</div><div class="card"><h4>Persönliche Daten</h4>Mehrere Komponenten geändert; Daten können für Freigaben und Sicherheitsinformationen relevant sein.</div><div class="card"><h4>Umsatzsuche</h4>Suche geändert; falsche Filter oder fehlende Umsätze möglich.<br><br><b>TF-US-18</b>: Filterkombination liefert unvollständige Trefferliste – <span class="badtext">FEHLGESCHLAGEN</span>.</div><div class="card"><h4>Elektronisches Postfach</h4>Begrenzte Änderung; neue Dokumente könnten vorübergehend nicht angezeigt werden.</div><div class="card"><h4>Profilbild</h4>Neue Funktion; Bild kann fehlen oder falsch dargestellt werden.</div></div><h3>Welche beiden Bereiche gehören nach diesen Angaben in hoch / hoch?</h3><div class="options"><button onclick="matrix(false)">Profilbild + Elektronisches Postfach</button><button onclick="matrix(false)">Umsatzsuche + Profilbild</button><button onclick="matrix(false)">Umsatzsuche + Elektronisches Postfach</button><button onclick="matrix(false)">Persönliche Daten + Profilbild</button><button onclick="matrix(true)">Überweisungen + Persönliche Daten</button></div><div id="fb"></div>`) }

function matrix(ok){document.querySelector('#fb').innerHTML=ok?msg('✓ Richtig – die beiden risikoreichsten Bereiche sind Überweisungen und Persönliche Daten.',true)+`<button class="primary" onclick="s6plan()">Weiter</button>`:msg('Eintrittswahrscheinlichkeit, Schadensausmaß und bisherige Testergebnisse gemeinsam berücksichtigen.')}

function s6plan(){panel(`<h2>Replanung</h2><div class="story">Es bleibt nicht mehr genug Zeit, um alle Themen vollständig zu testen. Eine Replanung ist erforderlich: Welche Bereiche sollen Henry, Lilia und Georg in den letzten Stunden bearbeiten?</div><div class="cards"><div class="card"><h4>Henry</h4>4 h</div><div class="card"><h4>Lilia</h4>4 h</div><div class="card"><h4>Georg</h4>4 h</div></div>${['Henry','Lilia','Georg'].map((n,i)=>`<div class="req"><b>${n} – 4 h</b><br><select id="p${i}"><option value="">– Bereich –</option><option>Überweisungen</option><option>Persönliche Daten</option><option>Umsatzsuche</option><option>Elektronisches Postfach</option><option>Profilbild</option></select></div>`).join('')}<button onclick="checkPlan()">Replanung speichern</button><div id="fb"></div>`) }

function checkPlan(){let a=[p0.value,p1.value,p2.value],hi=a.filter(x=>x==='Überweisungen'||x==='Persönliche Daten').length;document.querySelector('#fb').innerHTML=a.every(Boolean)&&hi>=2?msg('✓ 12 STUNDEN RISIKOORIENTIERT EINGEPLANT',true)+`<button class="primary" onclick="s6sick()">Plan speichern</button>`:msg('Bitte die Entscheidung noch einmal prüfen. Bereiche mit hohem Produktrisiko sollen deutlich berücksichtigt werden.')}

function s6sick(){setClock('Woche 2 · Donnerstag 13:42 Uhr');panel(`<h2>Neue E-Mail</h2><div class="mail"><b>VON:</b> Henry<br><b>BETREFF:</b> Ausfall für den Rest der Testphase<br><br>Hallo,<br><br>ich muss mich leider für den Rest der Testphase krankmelden.<br><br>Viele Grüße<br>Henry</div><div class="notice danger"><b>⚠ RESSOURCENABWEICHUNG</b><br>Geplante Kapazität: 12 h · Noch verfügbar: 8 h<br>Henry: NICHT VERFÜGBAR</div><h3>Wie soll reagiert werden?</h3><div class="options"><button id="decA" onclick="decision('A')">Verlust ignorieren; Plan unverändert lassen</button><button id="decB" onclick="decision('B')">Kapazität neu verteilen und risikoorientiert priorisieren</button><button id="decC" onclick="decision('C')">Projektleitung informieren und Ersatzkapazität prüfen</button><button id="decD" onclick="decision('D')">Release sofort stoppen</button></div><div id="fb"></div>`) }

function decision(x){document.querySelectorAll('[id^=dec]').forEach(b=>b.classList.remove('selected'));document.querySelector('#dec'+x)?.classList.add('selected');let f=document.querySelector('#fb');if(x==='B'){f.innerHTML=award('henryB',5)+msg('✓ Kapazität wird risikoorientiert neu verteilt. Die Auswirkungen werden anschließend dokumentiert.',true)+`<button onclick="s6status()">Weiter</button>`}else if(x==='C'){f.innerHTML=award('henryC',2)+msg('✓ Projektleitung informiert. Ersatzkapazität ist nicht verfügbar; die verbleibende Kapazität muss nun risikoorientiert neu verteilt werden.',true)+`<button onclick="s6status()">Weiter</button>`}else f.innerHTML=msg('Neuer Versuch – kann das stimmen?')}

function s6status(){setClock('Woche 2 · Donnerstag 17:28 Uhr');panel(`<h2>Teststatus – Auswirkungen dokumentieren</h2><div class="story">Für Freitag wird ein transparenter Überblick über nicht durchgeführte Tests und verbleibende Produktrisiken benötigt.</div><h3>Testfallportfolio</h3><select id="st1"><option value="">– wählen –</option><option>Alle geplanten Tests wurden durchgeführt.</option><option value="p">Geplante Tests konnten teilweise nicht durchgeführt werden.</option><option>Nur fehlgeschlagene Tests werden dokumentiert.</option><option>Nicht durchgeführte Tests werden als blockiert gewertet.</option></select><h3>Produktrisiko</h3><select id="st2"><option value="">– wählen –</option><option>Ist automatisch gesunken.</option><option value="r">Muss unter Berücksichtigung der nicht durchgeführten Tests erneut betrachtet werden.</option><option>Spielt nach der Replanung keine Rolle mehr.</option><option>Wird nur bei fehlgeschlagenen Tests dokumentiert.</option></select><h3>Testabschluss</h3><select id="st3"><option value="">– wählen –</option><option>Nicht durchgeführte Tests aus dem Bericht entfernen.</option><option value="t">Nicht durchgeführte Tests und daraus verbleibende Unsicherheiten transparent dokumentieren.</option><option>Nur erfolgreiche Testfälle in den Abschluss übernehmen.</option><option>Alle offenen Punkte automatisch als behoben markieren.</option></select><br><br><button onclick="statusCheck()">Teststatus aktualisieren</button><div id="fb"></div>`) }

function statusCheck(){let ok=st1.value==='p'&&st2.value==='r'&&st3.value==='t';document.querySelector('#fb').innerHTML=ok?msg('✓ TESTSTATUS AKTUALISIERT · Ressourcenausfall dokumentiert · Planung angepasst · nicht durchgeführte Tests gekennzeichnet · Produktrisiken zur Neubewertung vorgemerkt',true)+`<button class="primary" onclick="s7()">Endspurt</button>`:msg('Der Status muss Ressourcenausfall, nicht durchgeführte Tests und verbleibende Unsicherheit transparent abbilden.')}

function s7(){setClock('Woche 2 · Freitag 09:03 Uhr');award('s6',10);setP(7,'Woche 2 · Freitag');panel(`<div class="eyebrow">Station 7 · Freitag 09:03</div><h2>Der Testabschluss</h2>${meter(18,'TESTABSCHLUSSBERICHT VOLLSTÄNDIG')}<div class="notice bad">⚠ TESTABSCHLUSS UNVOLLSTÄNDIG · Einige Daten fehlen, andere widersprechen dem Testverlauf.</div><div class="split"><div class="file"><b>TESTKONZEPT</b><br>Testobjekt ✓<br>Zeitraum ✓<br>Testziele ✓<br>Testumfang ✓<br>Zentrale Testumgebung ✓<br>Henry · Lilia · Georg ✓<br>Überwachung/Steuerung ✓</div><div class="file"><b>ABSCHLUSSBERICHT</b><br>Testdurchführung [BESCHÄDIGT]<br>Testergebnisse [BESCHÄDIGT]<br>Fehlermeldungen [BESCHÄDIGT]<br>Planabweichungen [BESCHÄDIGT]<br>Produktrisiken [BESCHÄDIGT]<br>Testziele [BESCHÄDIGT]<br>Empfehlung [FEHLT]</div></div><button class="primary" onclick="s7numbers()">Bericht rekonstruieren</button>`)}
function s7numbers(){panel(`<h2>Wie viele Testfälle wurden durchgeführt?</h2><table><tr><td>Geplante Testfälle</td><td>240</td></tr><tr><td>Erfolgreich durchgeführt</td><td>144</td></tr><tr><td>Fehlgeschlagen</td><td>36</td></tr><tr><td>Blockiert</td><td>12</td></tr><tr><td>Nicht durchgeführt</td><td>48</td></tr></table><p>Tatsächlich durchgeführt: <input id="fn" type="number"> · Anteil: <input id="fp" type="number"> %</p><button onclick="numbers()">Prüfen</button><div id="fb"></div>`) }

function numbers(){let ok=+fn.value===180&&+fp.value===75;document.querySelector('#fb').innerHTML=ok?msg('✓ 180 von 240 geplanten Testfällen wurden durchgeführt = 75 %. 12 blockiert, 48 nicht durchgeführt.',true)+meter(31,'TESTABSCHLUSSBERICHT VOLLSTÄNDIG')+`<button class="primary" onclick="s7evidence()">Ergebnisarchiv öffnen</button>`:msg('Blockierte und nicht durchgeführte Testfälle zählen hier nicht als durchgeführt.')}
function s7evidence(){panel(`<h2>Fehlersituation</h2><div class="cards"><div class="card"><h4>FM-472</h4>Kontosperre nach Browseraktualisierung aufgehoben.<br><b>Schweregrad: hoch</b></div><div class="card"><h4>FM-486</h4>Zusätzliche Freigabe bei 1.001 € nicht angefordert.<br><b>Schweregrad: hoch</b></div><div class="card"><h4>FM-481</h4>Überweisungsvorlage kann nicht gespeichert werden.<br><b>Schweregrad: niedrig</b><br>Analyse: Systemverhalten entspricht der Vorgabe.</div></div><h3>Welche Risiken können im Abschlussbericht aufgenommen werden?</h3><div class="options"><button onclick="evidence('A')">Es bestehen keine verbleibenden Produktrisiken.</button><button onclick="evidence('C')">Alle festgestellten Situationen sind behoben, weil sie dokumentiert wurden.</button><button onclick="evidence('D')">Release 2.0 wurde als fehlerfrei nachgewiesen.</button><button onclick="evidence('E')">Die analysierte FM-481 muss als schwerwiegender Produktfehler bewertet werden.</button><button onclick="evidence('B')">Nicht alle geplanten Tests konnten durchgeführt werden; hoch bewertete Fehlersituationen und nicht durchgeführte Tests lassen verbleibende Produktrisiken und Unsicherheit bestehen.</button></div><div id="fb"></div>`) }

function evidence(x){document.querySelector('#fb').innerHTML=x==='B'?msg('✓ Risiken korrekt erkannt und benannt.',true)+meter(59,'TESTABSCHLUSSBERICHT VOLLSTÄNDIG')+`<button class="primary" onclick="s7goals()">Freigabebewertung</button>`:msg('Diese Aussage wird durch die vorliegenden Testinformationen nicht gestützt.')}

function s7plan(){panel(`<div class="eyebrow">Station 7 · Plan / Ist</div><h2>Abweichungen dokumentieren</h2><div class="req">Geplant: 3 Tester (Henry, Lilia, Georg)<br><b>Tatsächlich:</b> Henry fiel während der verbleibenden Testphase aus.</div><div class="req">Geplant: Testüberwachung und Teststeuerung<br><b>Tatsächlich:</b> Planung wurde aufgrund des Ressourcenausfalls angepasst.</div><div class="req">Geplant: Zentrale Testumgebung<br><b>Tatsächlich:</b> Testdurchführung in der vorgesehenen Umgebung.</div>${meter(59,'TESTABSCHLUSSBERICHT VOLLSTÄNDIG')}<button class="primary" onclick="s7goals()">Testziele bewerten</button>`)}
function s7goals(){panel(`<div class="eyebrow">Station 7 · Testziele</div><h2>Bewertung</h2><div class="file">Informationen über Qualität gewinnen · Anforderungen prüfen · Fehlerzustände/Fehlerwirkungen aufdecken · Informationen für Entscheidungen bereitstellen</div><div class="options"><button onclick="goals(false)">Alle Testziele vollständig erreicht, weil 75 % durchgeführt wurden.</button><button onclick="goals(false)">Kein Testziel erreicht, weil nicht alle Tests durchgeführt wurden.</button><button onclick="goals(true)">Die Tests lieferten Qualitätsinformationen und deckten Fehlerwirkungen auf; nicht durchgeführte und blockierte Tests lassen verbleibende Unsicherheit.</button></div><div id="fb"></div>`)}
function goals(ok){document.querySelector('#fb').innerHTML=ok?msg('✓ TESTZIELE BEWERTET',true)+meter(72,'TESTABSCHLUSSBERICHT VOLLSTÄNDIG')+`<button class="primary" onclick="s7risk()">Produktrisiken prüfen</button>`:msg('Der Durchführungsgrad ist nicht identisch mit der Zielerreichung.')}
function s7risk(){panel(`<div class="eyebrow">Station 7 · Produktrisiken</div><h2>Gespeicherter Status: „KEINE“</h2><div class="notice bad">⚠ WIDERSPRUCH ZU TESTERGEBNISSEN</div><div class="options"><button onclick="finalrisk(false)">Keine verbleibenden Produktrisiken.</button><button onclick="finalrisk(true)">Verbleibende Produktrisiken vorhanden; besonders bei Überweisungen bestehen wegen Abweichungen und nicht vollständig durchgeführter Tests Unsicherheiten.</button></div><div id="fb"></div>`)}
function finalrisk(ok){document.querySelector('#fb').innerHTML=ok?msg('✓ VERBLEIBENDE PRODUKTRISIKEN DOKUMENTIERT',true)+meter(86,'TESTABSCHLUSSBERICHT VOLLSTÄNDIG')+`<button class="primary" onclick="s7rec()">Empfehlung formulieren</button>`:msg('Festgestellte Abweichungen und nicht durchgeführte Tests lassen verbleibende Unsicherheit bestehen.')}
function s7rec(){panel(`<div class="eyebrow">Station 7 · Empfehlung der Testleitung</div><h2>Letztes fehlendes Feld</h2><div class="options"><button onclick="rec(false)">Release 2.0 kann ohne Einschränkungen produktiv gesetzt werden.</button><button onclick="rec(false)">Release 2.0 darf nicht produktiv gesetzt werden, weil nicht alle Tests durchgeführt wurden.</button><button onclick="rec(true)">Vor der Produktivsetzung sollten besonders die verbleibenden Unsicherheiten bei Überweisungen berücksichtigt werden. Ausstehende risikorelevante Tests sollten nach Möglichkeit nachgeholt bzw. das verbleibende Produktrisiko vor der Release-Entscheidung ausdrücklich bewertet werden.</button></div><div id="fb"></div>`)}
function rec(ok){document.querySelector('#fb').innerHTML=ok?msg('✓ EMPFEHLUNG DER TESTLEITUNG FORMULIERT',true)+meter(100,'TESTABSCHLUSSBERICHT VOLLSTÄNDIG')+`<div class="notice good">✓ Testergebnisse zusammengefasst<br>✓ Abweichungen dokumentiert<br>✓ Testziele bewertet<br>✓ Verbleibende Produktrisiken dargestellt<br>✓ Empfehlung formuliert</div><button class="primary" onclick="finish()">Abschlussbericht übermitteln</button>`:msg('Die Testleitung liefert eine begründete Entscheidungsgrundlage; sie trifft hier nicht selbst die Release-Entscheidung.')}
function finish(){setClock('Woche 2 · Freitag 15:58 Uhr');award('s7',20);panel(`<h1>Release 2.0</h1><h2>TESTPHASE ABGESCHLOSSEN</h2><div class="story mono">testabschluss_release20.pdf wird erzeugt …<br>Ergebnisse und verbleibende Risiken dokumentiert ✓<br>Freigabeempfehlung übermittelt ✓<br><span class="goodtext">✓ ERFOLGREICH</span></div><div class="notice good"><b>ENTSCHEIDUNG DER RELEASE-VERANTWORTLICHEN</b><br><br>Die Freigabeempfehlungen wurden eingeholt und unter Berücksichtigung der dokumentierten Einschränkungen bewertet.</div><div class="bigstatus center">RELEASE STATUS<br>RELEASE 2.0 FREIGEGEBEN<br><small>Produktivsetzung erfolgt · Gesammelte Credits: ${credits} / 100</small></div><div class="story center"><b>GESCHAFFT!</b><br>Release 2.0 ist gerettet.<br>Danke für die Unterstützung!</div><br><button onclick="start()">Spiel neu starten</button>`) }

start();
